/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package topicBrowser;

import java.awt.EventQueue;

import javax.swing.event.TreeSelectionEvent;
import javax.swing.event.TreeSelectionListener;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreeSelectionModel;

import exercise.ExerciseExample;
import exercise.ExerciseTemplate;
import exercise.ExerciseWindow;

public class TopicBrowserWindow extends javax.swing.JFrame {

	/**
	 * Creates new form topicBrowserWindow
	 */
	public TopicBrowserWindow() {
		initComponents();
	}

	public class Topic {
		public Topic(String topicNodeString, String topicClassString) {
			setTopicNodeString(topicNodeString);
			setTopicClassString(topicClassString);
		}

		private String topicNodeString;
		private String topicClassString;

		public void setTopicClassString(String topicClassString) {
			this.topicClassString = topicClassString;
		}

		public void setTopicNodeString(String topicNodeString) {
			this.topicNodeString = topicNodeString;
		}

		public String getTopicClassString() {
			return topicClassString;
		}

		public String getTopicNodeString() {
			return topicNodeString;
		}

		@Override
		public String toString() {
			return getTopicNodeString();
		}

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jDialog1 = new javax.swing.JDialog();
		jDialog2 = new javax.swing.JDialog();
		jLabel1 = new javax.swing.JLabel();
		jScrollPane2 = new javax.swing.JScrollPane();
		jTree1 = new javax.swing.JTree();

		javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(
				jDialog1.getContentPane());
		jDialog1.getContentPane().setLayout(jDialog1Layout);
		jDialog1Layout.setHorizontalGroup(jDialog1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 400,
				Short.MAX_VALUE));
		jDialog1Layout.setVerticalGroup(jDialog1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 300,
				Short.MAX_VALUE));

		javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(
				jDialog2.getContentPane());
		jDialog2.getContentPane().setLayout(jDialog2Layout);
		jDialog2Layout.setHorizontalGroup(jDialog2Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 400,
				Short.MAX_VALUE));
		jDialog2Layout.setVerticalGroup(jDialog2Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 300,
				Short.MAX_VALUE));

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setText("Topics");

		jTree1.setModel(new DefaultTreeModel(new DefaultMutableTreeNode("C") {
			{
				DefaultMutableTreeNode node_1;
				node_1 = new DefaultMutableTreeNode("Input/Output");
				node_1.add(new DefaultMutableTreeNode(new Topic(
						"Output: printf()", exercise.ExerciseExample.class
								.getName())));
				node_1.add(new DefaultMutableTreeNode("Input:     scanf()"));
				add(node_1);
				node_1 = new DefaultMutableTreeNode("Conditional Constructs");
				node_1.add(new DefaultMutableTreeNode("if"));
				node_1.add(new DefaultMutableTreeNode("if/elseif/else"));
				node_1.add(new DefaultMutableTreeNode("switch"));
				add(node_1);
				node_1 = new DefaultMutableTreeNode("Loops\t");
				node_1.add(new DefaultMutableTreeNode("while"));
				node_1.add(new DefaultMutableTreeNode("for"));
				add(node_1);
				add(new DefaultMutableTreeNode("Pointers"));
				add(new DefaultMutableTreeNode("Arrays"));
				add(new DefaultMutableTreeNode("Strings"));
				node_1 = new DefaultMutableTreeNode("Sorting");
				node_1.add(new DefaultMutableTreeNode("Search"));
				node_1.add(new DefaultMutableTreeNode("Bubble"));
				node_1.add(new DefaultMutableTreeNode("Insertion"));
				add(node_1);
				node_1 = new DefaultMutableTreeNode("File I/O");
				node_1.add(new DefaultMutableTreeNode("input"));
				node_1.add(new DefaultMutableTreeNode("output"));
				add(node_1);
			}
		}));
		jScrollPane2.setColumnHeaderView(jTree1);

		// set Single Selection only
		jTree1.getSelectionModel().setSelectionMode(
				TreeSelectionModel.SINGLE_TREE_SELECTION);

		// add TreeSelectionListener
		jTree1.addTreeSelectionListener(new TreeSelectionListener() {
			public void valueChanged(TreeSelectionEvent e) {
				DefaultMutableTreeNode node = (DefaultMutableTreeNode) jTree1
						.getLastSelectedPathComponent();
				if (node == null)
					return; /* Do Nothing */
				else
					System.out.println(node);
				if (node.getLevel() == 2) {
					// Moved from ExerciseWindow.main() (created by
					// WindowBuilder)
					EventQueue.invokeLater(new Runnable() {
						public void run() {
							try {
								ExerciseWindow frame = new ExerciseWindow(
										(ExerciseTemplate) Class.forName(
												((Topic) node.getUserObject())
														.getTopicClassString())
												.newInstance());
								frame.setVisible(true);
							} catch (ClassNotFoundException e) {
								e.printStackTrace();
							} catch (Exception e) {
								e.printStackTrace();
							}
						}
					});

				}
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(
														jScrollPane2,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														559,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel1))
								.addContainerGap(22, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jLabel1)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addComponent(jScrollPane2,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										299,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap()));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new TopicBrowserWindow().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JDialog jDialog1;
	private javax.swing.JDialog jDialog2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JTree jTree1;
	// End of variables declaration//GEN-END:variables
}
